"""
Markdown reporter module.
Generates human-readable Markdown summary reports.
"""

import logging
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime
from ..utils.helpers import format_bytes, format_currency, calculate_percentage

logger = logging.getLogger(__name__)


class MarkdownReporter:
    """Generates Markdown format reports."""
    
    def __init__(self, output_dir: str = "./reports"):
        """
        Initialize the reporter.
        
        Args:
            output_dir: Directory to save reports
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_report(
        self,
        assessment_summary: Dict[str, Any],
        filename: str = None
    ) -> str:
        """
        Generate Markdown summary report.
        
        Args:
            assessment_summary: Summary of assessment results
            filename: Optional custom filename
            
        Returns:
            Path to generated report file
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"storage_assessment_summary_{timestamp}.md"
        
        output_path = self.output_dir / filename
        
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                # Header
                f.write("# Azure Storage Assessment Report\n\n")
                f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n\n")
                
                # Executive Summary
                f.write("## Executive Summary\n\n")
                self._write_executive_summary(f, assessment_summary)
                
                # Key Findings
                f.write("\n## Key Findings\n\n")
                self._write_key_findings(f, assessment_summary)
                
                # Cost Analysis
                f.write("\n## Cost Analysis\n\n")
                self._write_cost_analysis(f, assessment_summary)
                
                # Security Overview
                f.write("\n## Security Overview\n\n")
                self._write_security_overview(f, assessment_summary)
                
                # Top Recommendations
                f.write("\n## Top Recommendations\n\n")
                self._write_recommendations(f, assessment_summary)
                
                # Storage Accounts Summary
                f.write("\n## Storage Accounts Summary\n\n")
                self._write_storage_accounts_table(f, assessment_summary)
                
                # Footer
                f.write("\n---\n")
                f.write("\n*This report was generated by the Azure Storage Assessment Toolkit.*\n")
                f.write("*For detailed data, refer to the CSV and JSON reports.*\n")
            
            logger.info(f"Markdown report generated: {output_path}")
            return str(output_path)
            
        except Exception as e:
            logger.error(f"Failed to generate Markdown report: {e}")
            raise
    
    def _write_executive_summary(self, f, summary: Dict):
        """Write executive summary section."""
        stats = summary.get('statistics', {})
        
        f.write(f"- **Total Storage Accounts:** {stats.get('total_storage_accounts', 0)}\n")
        f.write(f"- **Total Subscriptions:** {stats.get('total_subscriptions', 0)}\n")
        f.write(f"- **Total Containers:** {stats.get('total_containers', 0)}\n")
        f.write(f"- **Total File Shares:** {stats.get('total_file_shares', 0)}\n")
        f.write(f"- **Total Blobs:** {stats.get('total_blobs', 0):,}\n")
        f.write(f"- **Total Capacity:** {format_bytes(stats.get('total_capacity_bytes', 0))}\n")
        f.write(f"- **Estimated Monthly Cost:** {format_currency(stats.get('total_monthly_cost', 0))}\n")
        f.write(f"- **Potential Monthly Savings:** {format_currency(stats.get('total_monthly_savings', 0))} ")
        
        savings_percent = calculate_percentage(
            stats.get('total_monthly_savings', 0),
            stats.get('total_monthly_cost', 0)
        )
        f.write(f"({savings_percent:.1f}%)\n")
    
    def _write_key_findings(self, f, summary: Dict):
        """Write key findings section."""
        findings_stats = summary.get('findings_statistics', {})
        
        critical_count = findings_stats.get('critical', 0)
        high_count = findings_stats.get('high', 0)
        medium_count = findings_stats.get('medium', 0)
        
        if critical_count > 0:
            f.write(f"🔴 **CRITICAL:** {critical_count} critical security/governance issue(s) found\n\n")
        
        if high_count > 0:
            f.write(f"🟠 **HIGH:** {high_count} high-severity issue(s) require attention\n\n")
        
        if medium_count > 0:
            f.write(f"🟡 **MEDIUM:** {medium_count} medium-severity issue(s) identified\n\n")
        
        # Specific findings
        stats = summary.get('statistics', {})
        
        if stats.get('accounts_with_public_access', 0) > 0:
            f.write(f"⚠️ {stats.get('accounts_with_public_access', 0)} storage account(s) allow public blob access\n\n")
        
        if stats.get('accounts_without_https_only', 0) > 0:
            f.write(f"⚠️ {stats.get('accounts_without_https_only', 0)} storage account(s) do not enforce HTTPS-only\n\n")
        
        if stats.get('accounts_without_soft_delete', 0) > 0:
            f.write(f"⚠️ {stats.get('accounts_without_soft_delete', 0)} storage account(s) do not have soft delete enabled\n\n")
        
        stale_size_gb = stats.get('total_stale_size_bytes', 0) / (1024 ** 3)
        if stale_size_gb > 1:
            f.write(f"💾 {format_bytes(stats.get('total_stale_size_bytes', 0))} of stale data detected (90+ days no access)\n\n")
    
    def _write_cost_analysis(self, f, summary: Dict):
        """Write cost analysis section."""
        stats = summary.get('statistics', {})
        
        f.write(f"**Current Monthly Cost:** {format_currency(stats.get('total_monthly_cost', 0))}\n\n")
        f.write(f"**Potential Monthly Savings:** {format_currency(stats.get('total_monthly_savings', 0))}\n\n")
        f.write(f"**Potential Annual Savings:** {format_currency(stats.get('total_monthly_savings', 0) * 12)}\n\n")
        
        # Breakdown by tier
        tier_costs = stats.get('tier_cost_breakdown', {})
        if tier_costs:
            f.write("### Storage by Tier\n\n")
            f.write("| Tier | Size | Monthly Cost |\n")
            f.write("|------|------|-------------|\n")
            
            for tier, data in tier_costs.items():
                size = format_bytes(data.get('size_bytes', 0))
                cost = format_currency(data.get('cost', 0))
                f.write(f"| {tier} | {size} | {cost} |\n")
            f.write("\n")
    
    def _write_security_overview(self, f, summary: Dict):
        """Write security overview section."""
        stats = summary.get('statistics', {})
        
        avg_security_score = stats.get('average_security_score', 0)
        
        if avg_security_score >= 80:
            emoji = "🟢"
            rating = "GOOD"
        elif avg_security_score >= 60:
            emoji = "🟡"
            rating = "FAIR"
        else:
            emoji = "🔴"
            rating = "NEEDS IMPROVEMENT"
        
        f.write(f"{emoji} **Average Security Score:** {avg_security_score:.1f}/100 ({rating})\n\n")
        
        f.write("### Security Configuration Status\n\n")
        f.write(f"- **HTTPS-Only Enforced:** {stats.get('accounts_with_https_only', 0)}/{stats.get('total_storage_accounts', 0)} accounts\n")
        f.write(f"- **Public Access Disabled:** {stats.get('accounts_without_public_access', 0)}/{stats.get('total_storage_accounts', 0)} accounts\n")
        f.write(f"- **Soft Delete Enabled:** {stats.get('accounts_with_soft_delete', 0)}/{stats.get('total_storage_accounts', 0)} accounts\n")
        f.write(f"- **Versioning Enabled:** {stats.get('accounts_with_versioning', 0)}/{stats.get('total_storage_accounts', 0)} accounts\n")
        f.write(f"- **Minimum TLS 1.2:** {stats.get('accounts_with_tls12', 0)}/{stats.get('total_storage_accounts', 0)} accounts\n")
    
    def _write_recommendations(self, f, summary: Dict):
        """Write top recommendations section."""
        recommendations = summary.get('top_recommendations', [])
        
        if not recommendations:
            f.write("No specific recommendations at this time.\n")
            return
        
        for i, rec in enumerate(recommendations[:10], 1):
            severity = rec.get('severity', 'info').upper()
            emoji = self._get_severity_emoji(rec.get('severity', 'info'))
            storage_account = rec.get('storage_account', 'N/A')
            
            f.write(f"{i}. {emoji} **[{severity}]** {rec.get('title', 'No title')}\n")
            f.write(f"   - **Storage Account:** `{storage_account}`\n")
            f.write(f"   - **Finding:** {rec.get('finding', 'N/A')}\n")
            f.write(f"   - **Impact:** {rec.get('impact', 'N/A')}\n")
            f.write(f"   - **Recommendation:** {rec.get('recommendation', 'N/A')}\n")
            
            if rec.get('estimated_savings'):
                f.write(f"   - **Potential Savings:** {format_currency(rec.get('estimated_savings', 0))}/month\n")
            
            f.write("\n")
    
    def _write_storage_accounts_table(self, f, summary: Dict):
        """Write storage accounts summary table."""
        accounts = summary.get('storage_accounts_summary', [])
        
        if not accounts:
            f.write("No storage accounts found.\n")
            return
        
        # Compact table with most important columns
        f.write("| Account Name | Region | Size | Resources | Security | Monthly Cost |\n")
        f.write("|--------------|--------|------|-----------|----------|-------------|\n")
        
        for account in accounts[:50]:  # Limit to first 50 for readability
            name = account.get('name', 'N/A')
            location = account.get('location', 'N/A')
            size = format_bytes(account.get('size_bytes', 0))
            containers = account.get('container_count', 0)
            shares = account.get('share_count', 0)
            security_score = account.get('security_score', 0)
            monthly_cost = format_currency(account.get('monthly_cost', 0))
            
            # Combine containers/shares into single column
            resources = f"{containers}c/{shares}s" if containers or shares else "-"
            
            # Security score with emoji indicator
            if security_score >= 80:
                security_display = f"🟢 {security_score:.0f}"
            elif security_score >= 60:
                security_display = f"🟡 {security_score:.0f}"
            else:
                security_display = f"🔴 {security_score:.0f}"
            
            f.write(f"| {name} | {location} | {size} | {resources} | {security_display} | {monthly_cost} |\n")
        
        if len(accounts) > 50:
            f.write(f"\n*Showing 50 of {len(accounts)} storage accounts. See CSV report for complete list.*\n")
        
        # Add legend
        f.write("\n*Resources: c=containers, s=shares | Security: 🟢 Good (80+), 🟡 Fair (60-79), 🔴 Needs Improvement (<60)*\n")
    
    def _get_severity_emoji(self, severity: str) -> str:
        """Get emoji for severity level."""
        emoji_map = {
            'critical': '🔴',
            'high': '🟠',
            'medium': '🟡',
            'low': '🟢',
            'info': 'ℹ️'
        }
        return emoji_map.get(severity.lower(), '📌')
